### ISSUE TITLE
Convert LESS to SCSS

### ISSUE THREAD

**Issue by clementallen** [clementallen/arcadian#29]
Currently the website styles are in LESS but I would prefer them converted to SCSS.

A similar piece of work was completed which can be used as guidance: redbrick/techweek.dcu.ie#35

**Work required**
- [x] Convert `.less` files to `.scss` and make them compatible with the different syntax.
- [x] Update `gulp` to compile scss instead of less

**Set up local environment**
- check out repository
- run `npm install`
- run `gulp`
- run `node bin/www`
- visit `http://localhost:3003` in your browser

**Comment by jordanbrauer** [comment]
Hey man, you still looking for someone to do this? I can convert `.less` to `.scss` pretty fast. Just did an icon font conversion yesterday in about 10 hours lol. :)

**Comment by clementallen** [comment]
@jordanbrauer yes please! I'd do it myself but just don't have the time. Cheers

**Comment by jordanbrauer** [comment]
@clementallen Sweet! I shall get started. Do you have a preference on how I submit my pull request? (master branch, new branch?).

Also, do I have the freedom to enhance the code as well as convert it?

**Comment by clementallen** [comment]
@jordanbrauer A pr from a forked version into master would be great.

Please feel free to enhance any areas you see fit!

**Comment by themaxsandelin** [comment]
Is this issue still up for grabs? :)

**Comment by clementallen** [comment]
@themaxsandelin I believe @jordanbrauer is working on it as per his comment above

**Comment by themaxsandelin** [comment]
@clementallen Thanks for letting me know :)

**Comment by jordanbrauer** [comment]
@clementallen Just so you know, you haven't provided a `sample.config.js` file for contributors to fill out the necessary local development credentials in order to run your node server. If you could provide one with instructions on what to fill out for local development, that would be much appreciated. :)

**Comment by clementallen** [comment]
@jordanbrauer oops my apologies!

I've added a `sample.config.js` in the `config/` directory.  Just copy that to `config.js` and everything should run fine.

**Comment by jordanbrauer** [comment]
@clementallen w00t, thanks man.

**Comment by clementallen** [comment]
Closed via the merging of #30 

Many thanks @jordanbrauer, some excellent Sassifying! (if that's a word) 🎉
